export const OnePlayerGames = ['Expeditions', 'Fire_Tower', 'Scythe', 'Wingspan'];
export const TwoPlayerGames = [
  'six_Qui_Surprend',
  'Azul',
  'Battleship',
  'Carcassone',
  'Chess',
  'Codenames_Duet',
  'Connect_four',
  'Expeditions',
  'Exploding_Kittens',
  'Falling_Monkeys',
  'Fire_Tower',
  'Jenga',
  'Lets_get_deep_couples',
  'Lets_get_deep_friends',
  'Mastermind',
  'Micado',
  'Mini_Plakks',
  'Monopoly',
  'Monopoly_Bid',
  'Monopoly_Deal',
  'Monopoly_Ultimate_Banking',
  'Mot_Meles',
  'Pandamic',
  'Pear_Shaped',
  'Quatro',
  'Quoridor',
  'Risk',
  'Risk_Games_of_Thrones',
  'Rummikub',
  'Scythe',
  'Seven_Wonders',
  'Seven_Wonders_Duel',
  'Splendor_Marvel',
  'Squadro',
  'Stratego',
  'Sudoku',
  'Taco_vs_Burrito',
  'Tawlit_Zaher',
  'The_Mind',
  'The_Mind_Extreme',
  'Ticket_to_Ride',
  'Ticket_to_Ride_Europe',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'Wingspan',
  'You_re_getting_old',
  'You_re_getting_saucy',
  'You_re_getting_stupid',
  'Zombie_Kittens',
];

export const ThreePlayerGames = [
  'six_Qui_Surprend',
  'Azul',
  'Catan',
  'Carcassone',
  'Dixit',
  'Expeditions',
  'Exploding_Kittens',
  'Falling_Monkeys',
  'Fire_Tower',
  'Hedbanz',
  'Jenga',
  'Lets_get_deep_friends',
  'Monopoly',
  'Monopoly_Bid',
  'Monopoly_Deal',
  'Monopoly_Ultimate_Banking',
  'Mot_Meles',
  'Pandamic',
  'Pear_Shaped',
  'Priorities',
  'Risk',
  'Risk_Games_of_Thrones',
  'Rummikub',
  'Scythe',
  'Seven_Wonders',
  'Splendor_Marvel',
  'Sudoku',
  'Taco_vs_Burrito',
  'Tag_someone_who',
  'The_Mind',
  'The_Mind_Extreme',
  'The_voting_game',
  'Ticket_to_Ride',
  'Ticket_to_Ride_Europe',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'Wingspan',
  'Yellowstone',
  'You_re_getting_old',
  'You_re_getting_saucy',
  'You_re_getting_stupid',
  'Zombie_Kittens',
];
export const FourPlayerGames = [
  'six_Qui_Surprend',
  'Arrir_ma_tbarrir',
  'Azul',
  'Box_against_office',
  'Catan',
  'Carcassone',
  'Card_Against_Disney',
  'Cards_Against_Humanity',
  'Cards_Against_Potter',
  'Cards_against_star_wars',
  'Codenames_pictures',
  'Dixit',
  'El_mamnou3_marghoub',
  'Expeditions',
  'Exploding_Kittens',
  'Falling_Monkeys',
  'Fire_Tower',
  'Hedbanz',
  'Jenga',
  'Lets_get_deep_friends',
  'Machrou3_Ra2is',
  'Monopoly',
  'Monopoly_Bid',
  'Monopoly_Deal',
  'Monopoly_Ultimate_Banking',
  'Mot_Meles',
  'Murder_we_wrote',
  'Pandamic',
  'Pear_Shaped',
  'Priorities',
  'Risk',
  'Risk_Games_of_Thrones',
  'Rummikub',
  'Scythe',
  'Seven_Wonders',
  'Splendor_Marvel',
  'Sudoku',
  'Taco_vs_Burrito',
  'Tag_someone_who',
  'The_Mind',
  'The_Mind_Extreme',
  'The_voting_game',
  'Ticket_to_Ride',
  'Ticket_to_Ride_Europe',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'What_do_you_meme',
  'Wingspan',
  'Yellowstone',
  'You_re_getting_old',
  'You_re_getting_saucy',
  'You_re_getting_stupid',
  'Zello_ma_t2ello',
  'Zombie_Kittens',
];
export const FivePlayerGames = [
  'six_Qui_Surprend',
  'Arrir_ma_tbarrir',
  'Avalon',
  'Box_against_office',
  'Catan',
  'Carcassone',
  'Card_Against_Disney',
  'Cards_Against_Humanity',
  'Cards_Against_Potter',
  'Cards_against_star_wars',
  'Codenames_pictures',
  'Dixit',
  'El_mamnou3_marghoub',
  'Expeditions',
  'Exploding_Kittens',
  'Fire_Tower',
  'Hedbanz',
  'Lets_get_deep_friends',
  'Machrou3_Ra2is',
  'Monopoly',
  'Monopoly_Bid',
  'Monopoly_Deal',
  'Monopoly_Ultimate_Banking',
  'Murder_we_wrote',
  'Pandamic',
  'Pear_Shaped',
  'Priorities',
  'Risk',
  'Risk_Games_of_Thrones',
  'Scythe',
  'Secret_Hitler',
  'Seven_Wonders',
  'Sudoku',
  'Tag_someone_who',
  'The_voting_game',
  'Ticket_to_Ride',
  'Ticket_to_Ride_Europe',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'What_do_you_meme',
  'Wingspan',
  'Yellowstone',
  'You_re_getting_old',
  'You_re_getting_saucy',
  'You_re_getting_stupid',
  'Zello_ma_t2ello',
  'Zombie_Kittens',
];
export const SixPlayerGames = [
  'six_Qui_Surprend',
  'Arrir_ma_tbarrir',
  'Avalon',
  'Box_against_office',
  'Catan',
  'Card_Against_Disney',
  'Cards_Against_Humanity',
  'Cards_Against_Potter',
  'Cards_against_star_wars',
  'Codenames_pictures',
  'Dixit',
  'El_mamnou3_marghoub',
  'Exploding_Kittens',
  'Hedbanz',
  'Lets_get_deep_friends',
  'Machrou3_Ra2is',
  'Monopoly',
  'Monopoly_Ultimate_Banking',
  'Murder_we_wrote',
  'Pear_Shaped',
  'Priorities',
  'Risk_Games_of_Thrones',
  'Secret_Hitler',
  'Seven_Wonders',
  'Sudoku',
  'Tag_someone_who',
  'The_voting_game',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'What_do_you_meme',
  'Yellowstone',
  'You_re_getting_old',
  'You_re_getting_saucy',
  'You_re_getting_stupid',
  'Zello_ma_t2ello',
];

export const SevenPlayerGames = [
  'six_Qui_Surprend',
  'Arrir_ma_tbarrir',
  'Avalon',
  'Box_against_office',
  'Card_Against_Disney',
  'Cards_Against_Humanity',
  'Cards_Against_Potter',
  'Cards_against_star_wars',
  'Codenames_pictures',
  'El_mamnou3_marghoub',
  'Exploding_Kittens',
  'Lets_get_deep_friends',
  'Monopoly',
  'Pear_Shaped',
  'Priorities',
  'Risk_Games_of_Thrones',
  'Secret_Hitler',
  'Seven_Wonders',
  'Sudoku',
  'Tag_someone_who',
  'The_voting_game',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'What_do_you_meme',
  'Yellowstone',
  'Zello_ma_t2ello',
];
export const EightPlayerGames = [
  'six_Qui_Surprend',
  'Arrir_ma_tbarrir',
  'Avalon',
  'Box_against_office',
  'Card_Against_Disney',
  'Cards_Against_Humanity',
  'Cards_Against_Potter',
  'Cards_against_star_wars',
  'Codenames_pictures',
  'El_mamnou3_marghoub',
  'Exploding_Kittens',
  'Lets_get_deep_friends',
  'Monopoly',
  'Pear_Shaped',
  'Priorities',
  'Secret_Hitler',
  'Sudoku',
  'Tag_someone_who',
  'The_voting_game',
  'Tossit',
  'Uno',
  'Uno_Dare',
  'Uno_Flip',
  'Uno_Wild',
  'What_do_you_meme',
  'Yellowstone',
  'Zello_ma_t2ello',
];
export const Games = {
  /*
  Game_Name:[
  'Game Name',
  'Category',
  'Duration',
  'Description',
  'Tutorial',
  'Trailer',
  ]
  */
  Expeditions: [
    'Expeditions',
    'Deck-Building',
    '45-100 mins',
    'Expeditions is a cooperative card game where players embark on daring adventures to explore uncharted territories, strategically managing resources, overcoming challenges, and working together to complete expeditions and uncover hidden treasures.',
    'https://www.youtube.com/watch?v=YyLBa5DXi1w&t=14s',
    'https://www.youtube.com/watch?v=fL4PP8HR6aw',
  ],
  Fire_Tower: [
    'Fire Tower',
    'Tile Laying',
    '25-45mins',
    'Rising Flames is an expansion for Fire Tower, adding new challenges and features to the base game. Players face intensified wildfires, new strategic options, and additional tools to combat the blaze, enhancing the cooperative firefighting experience.',
    'https://www.youtube.com/watch?v=NRUfgHZQHp4',
    'https://www.youtube.com/watch?v=A89awPNEhMk',
  ],
  Scythe: [
    'Scythe',
    'Eurogame',
    '60-120 mins',
    'Scythe is a strategic board game set in an alternate history 1920s Europe, where players lead factions to expand their empires, harvest resources, build mechs, and vie for control of territory, all while balancing military might, economic prosperity, and diplomatic relations.',
    'https://www.youtube.com/watch?v=ffMLIL5qGQg',
    'https://www.youtube.com/watch?v=yPImGUz-p8U',
  ],
  Wingspan: [
    'Wingspan',
    'Deck-Building',
    '30-60 mins',
    'Wingspan is a board game focused on birdwatching and habitat creation, where players compete to attract a diverse array of bird species to their wildlife reserves, strategically managing resources and abilities to maximize points and build the most impressive aviary.',
    'https://www.youtube.com/watch?v=lgDgcLI2B0U',
    'https://www.youtube.com/watch?v=P_vF5yQicoI&list=PL8FIBt9V_BnsuIM7z9t7pjBUEzMsp5tSW&index=32',
  ],
  Azul: [
    'Azul',
    'Tile-Laying',
    '20-45 mins',
    'Azul is a tile-drafting board game where players compete to decorate the walls of the Royal Palace of Evora with vibrant ceramic tiles. Players strategically select and place tiles to complete sets and patterns, aiming to score the most points and create the most visually stunning mosaic.',
    'https://www.youtube.com/watch?v=y0sUnocTRrY',
    'https://www.youtube.com/shorts/3YRbhpbU4-E',
  ],
  Catan: [
    'Catan',
    'Eurogame',
    '45-160 mins',
    'Catan, also known as Settlers of Catan, is a strategic board game where players compete to establish settlements, build roads, and collect resources on an island. Through trading, negotiation, and careful planning, players aim to expand their territory, earn victory points, and become the dominant force on the island.',
    'https://www.youtube.com/watch?v=oiQ6SgBzfqY',
    'https://www.youtube.com/watch?v=5-6OVXTzVdI',
  ],
  Monopoly: [
    'Monopoly',
    'Classic',
    '45-60 mins',
    'Monopoly is a classic board game where players roll dice, move around the board, and buy, trade, and develop properties to amass wealth. The goal is to bankrupt opponents by charging them rent when they land on owned properties, ultimately becoming the last player with money and assets remaining.',
    'https://www.youtube.com/watch?v=AuWvMgYv03g',
    '',
  ],
  Risk: [
    'Risk',
    'Classic',
    '45-120 mins',
    'Risk is a classic board game of global conquest where players deploy armies, strategize their moves, and engage in battles to conquer territories and continents. The objective is to eliminate opponents and dominate the world map through strategic positioning, alliances, and calculated risk-taking.',
    'https://www.youtube.com/watch?v=Xo8RSozX6Ac',
    'https://www.youtube.com/watch?v=PN_gZsf6Rgc',
  ],
  Pandamic: [
    'Pandamic',
    'Co-op',
    '45-60 mins',
    'Pandemic is a cooperative board game where players work together as members of a disease control team to prevent global outbreaks and find cures for four deadly diseases. Players must collaborate to manage outbreaks, share knowledge, and travel the world to contain the diseases before they spread out of control and cause a pandemic.',
    'https://www.youtube.com/watch?v=ojkScPkdgsk',
    'https://www.youtube.com/shorts/9vYOHJS8dUI',
  ],
  Uno: [
    'Uno',
    'Classic',
    'Unlimited',
    'Uno is a classic card game where players aim to be the first to empty their hand of cards by matching them in color, number, or action. Players strategically play cards, sabotage opponents with action cards like skips and reverses, and race to call "Uno" when they have one card left, all while trying to avoid drawing penalty cards.',
  ],
  Uno_Flip: [
    'Uno Flip',
    'Card',
    'Unlimited',
    'Uno Flip is a variation of the classic Uno card game, featuring a double-sided deck with both light and dark cards. Players must strategically manage their hand as they switch between the two sides of the deck, utilizing action cards to thwart opponents and race to be the first to empty their hand. Uno Flip adds a twist to the traditional Uno gameplay with its dynamic card mechanics and strategic decision-making.',
  ],
  Uno_Dare: [
    'Uno Dare',
    'Card',
    'Unlimited',
    'Uno Dare is a version of the classic Uno card game that incorporates dares and challenges into gameplay. Players draw special Dare cards that instruct them to perform various actions or challenges, adding an unpredictable and exciting element to the game. Players must balance completing dares with traditional Uno gameplay, adding a fun twist to the familiar mechanics.',
  ],
  Uno_Wild: [
    'Uno Wild',
    'Card',
    'Unlimited',
    'Uno All Wild is a variation of the classic Uno card game where all cards in the deck are wild, meaning they can be played as any color or number. This variation typically leads to fast-paced and unpredictable gameplay, as players can strategically use wild cards to change the color or number of the cards in play. Uno All Wild adds an extra layer of excitement and strategy to the traditional Uno experience.',
  ],

  Jackaroo: [
    'Jackaroo',
    'Card',
    '30-100 mins',
    'Jackaroo is a CO-OP card game where you use a regular 52 deck of cards to get four marbels from you base to your home',
  ],

  Splendor_Marvel: [
    'Splendor Marvel',
    'Engine-Building',
    '30-45 mins',
    'Splendor Marvel Edition is a special version of the popular board game Splendor, featuring Marvel Comics characters and themes. In Splendor, players take on the roles of Renaissance-era gem merchants, acquiring gems and developing their gem mines to attract influential patrons and earn prestige points. In the Marvel Edition, the game retains the core mechanics of Splendor but incorporates Marvel superheroes and villains as characters and artwork, offering a fresh thematic experience for fans of both Splendor and Marvel Comics.',
    'https://www.youtube.com/watch?v=6HElLa-0Buw&t=561s',
    'https://www.youtube.com/watch?v=4JvAWJbxvuU',
  ],
  Ticket_to_Ride: [
    'Ticket to Ride',
    'Eurogame',
    '30-60 mins',
    'Ticket to Ride is a board game where players compete to build railway routes across a map, earning points by connecting cities and completing destination tickets while strategically blocking opponents.',
    'https://www.youtube.com/watch?v=4JhFhyvGdik',
    'https://www.youtube.com/watch?v=rvEnbdTDsjA',
  ],
  Ticket_to_Ride_Europe: [
    'Ticket to Ride Europe',
    'Eurogame',
    '30-60 mins',
    'Ticket to Ride is a board game where players compete to build railway routes across a map, earning points by connecting cities and completing destination tickets while strategically blocking opponents.',
    'https://www.youtube.com/watch?v=difSEK9A6f0',
    'https://www.youtube.com/watch?v=Q0bWLcr-gX4',
  ],
  Cards_Against_Humanity: [
    'Cards Against Humanity',
    'Party',
    'unlimited',
    'Hilarious, irreverent party game where players match cards to create outrageous and politically incorrect phrases.',
  ],
  Card_Against_Disney: [
    'Card Against Disney',
    'Party',
    'unlimited',
    'Hilarious, irreverent party game where players match cards to create outrageous and politically incorrect phrases.',
  ],
  Cards_Against_Potter: [
    'Cards Against Potter',
    'Party',
    'unlimited',
    'Hilarious, irreverent party game where players match cards to create outrageous and politically incorrect phrases.',
  ],
  Monopoly_Deal: [
    'Monopoly Deal',
    'Card',
    '20-45 mins',
    'Fast-paced card game adaptation of Monopoly, where players collect properties, charge rent, and sabotage opponents to become the wealthiest tycoon.',
    'https://www.youtube.com/watch?v=Gc0XrTjmCV8',
    'https://www.youtube.com/shorts/zgI7kQjoY_Y',
  ],
  Seven_Wonders: [
    'Seven Wonders',
    'Civilization',
    '30-45 mins',
    'Strategic card-drafting game where players build ancient civilizations, erect magnificent wonders, and outmaneuver opponents to achieve greatness.',
    'https://www.youtube.com/watch?v=XnBLz61FJYw',
    'https://www.youtube.com/watch?v=zenJxRYuOIM',
  ],
  Exploding_Kittens: [
    'Exploding Kittens',
    'Party',
    '15-45 mins',
    'Fast-paced, unpredictable card game where players avoid explosive kittens, use various actions, and sabotage opponents to be the last one standing.',
    'https://www.youtube.com/watch?v=kAkRKuv5Rts',
    'https://www.youtube.com/watch?v=ho-4ebTbLyU',
  ],
  Jenga: [
    'Jenga',
    'Party',
    '15-20 mins',
    'Tower-building game of skill and suspense, where players take turns removing blocks and balancing them on top to avoid collapse.',
    'https://www.youtube.com/watch?v=RtGYWqx_MYI',
    'https://www.youtube.com/watch?v=k5y-JlNOj9g',
  ],
  Monopoly_Bid: [
    'Monopoly Bid',
    'Card',
    '20-45 mins',
    'Fast-paced card game where players compete in bidding wars, collecting property sets and strategic action cards to outsmart opponents and dominate the auction.',
    'https://www.youtube.com/watch?v=cPwhYYSoTKc',
    'https://www.youtube.com/watch?v=HR66Oku8JjI',
  ],
  Zombie_Kittens: [
    'Zombie Kittens',
    'Party',
    '15-30 mins',
    'Card game of survival and chaos, where players navigate through zombie-infested scenarios, use tactical cards, and avoid being infected by the undead kittens.',
    'https://www.youtube.com/watch?v=AzUHlKC1-NY',
    'https://www.youtube.com/watch?v=rES-F-KJJfY',
  ],
  Secret_Hitler: [
    'Secret Hitler',
    'Social',
    '15-30 mins',
    'Social deduction game of deception and intrigue, where players work together to uncover hidden fascists while avoiding the rise of Hitler in pre-war Germany.',
    'https://www.youtube.com/watch?v=mbGXIDYdtas',
    'https://www.youtube.com/watch?v=8--U3byECAI',
  ],
  The_Mind: [
    'The Mind',
    'Social',
    '15-30 mins',
    ' Cooperative card game where players must communicate without words to play cards in ascending order, testing their intuition and synchronization.',
    'https://www.youtube.com/watch?v=uXl8MC0GMYE',
    'https://www.youtube.com/watch?v=i57p_2O7cTQ',
  ],
  The_Mind_Extreme: [
    'The Mind Extreme',
    'Social',
    '15-30 mins',
    'Intense version of The Mind with added challenges and twists, pushing players telepathic abilities to the limit.',
    'https://www.youtube.com/watch?v=SgKqHLhOFhI',
    '',
  ],
  You_re_getting_old: [
    "You're getting old",
    'Social',
    '30-45 mins',
    "A party game where players guess each other's opinions on humorous and absurd scenarios, leading to laughter-filled debates and revelations.",
    'https://www.youtube.com/watch?v=TL1SwzgizsM',
    'https://www.youtube.com/watch?v=TL1SwzgizsM',
  ],
  You_re_getting_stupid: [
    "You're getting stupid",
    'Social',
    '30-45 mins',
    "A party game where players guess each other's opinions on humorous and absurd scenarios, leading to laughter-filled debates and revelations.",
    'https://www.youtube.com/watch?v=TL1SwzgizsM',
    'https://www.youtube.com/watch?v=TL1SwzgizsM',
  ],
  You_re_getting_saucy: [
    "You're getting saucy",
    'Social',
    '30-45 mins',
    "A party game where players guess each other's opinions on humorous and absurd scenarios, leading to laughter-filled debates and revelations.",
    'https://www.youtube.com/watch?v=TL1SwzgizsM',
    'https://www.youtube.com/watch?v=TL1SwzgizsM',
  ],
  Lets_get_deep_couples: [
    'lets get deep couples',
    'Social',
    'unlimited',
    'A thought-provoking game designed for couples, encouraging intimate conversations and deeper connections through meaningful questions and prompts.',
  ],
  Pear_Shaped: [
    'Pear Shaped',
    'Party',
    '10-15 mins',
    'A party game that challenges player to finish their cards as fast as possible while facing some challenges on the way',
    '',
    'https://www.youtube.com/watch?v=43OtatO7yPo',
  ],
  What_do_you_Meme: [
    'What do you Meme',
    'Party',
    'unlimited',
    'A meme-based party game where players compete to create the funniest captions for popular internet memes, sparking laughter and creativity among friends.',
  ],
  Lets_get_deep_friends: [
    'lets get deep friends',
    'Social',
    'unlimited',
    'A social game designed for friends to spark meaningful conversations and strengthen bonds through thought-provoking questions and shared experiences.',
  ],
  six_Qui_Surprend: [
    '6 qui surprend',
    'Card',
    '15-20 mins',
    "A fast-paced card game where players race to avoid picking up penalty points by strategically playing cards and predicting their opponents' moves, leading to suspenseful and unpredictable gameplay.",
  ],
  Pictionary: [
    'Pictionary',
    'Party',
    'unlimited',
    'A classic drawing and guessing game where players take turns sketching clues and guessing what their teammates are drawing, fostering creativity, communication, and laughter.',
  ],

  Arrir_Ma_Tbarrir: [
    'Arrir Ma Tbarrir',
    'Party',
    'unlimited',
    'Choose between two hillarious and outrageous suggestions, 3 different gameplays are available for this game',
  ],
  Zello_ma_T2ello: [
    'Zello ma T2ello',
    'Party',
    'unlimited',
    'A social game where your goal is to embarrass your friends',
  ],
  Fhemet_3alek: [
    'Fhemet 3alek',
    'Party',
    '15-20 mins',
    'A word association game where players give one-word clues to help their teammates identify secret agents hidden among a grid of words, while avoiding clues that might lead them to innocent bystanders or enemy agents, requiring teamwork, creativity, and deductive reasoning to win.',
  ],
  Hzar_Chou: [
    'Hzar Chou',
    'Party',
    'unlimited',
    'A lebanese version of charades, mime what you read and let your team guess as many words as possible withine the target time',
  ],

  Le3be_3akroute: [
    'Le3be 3akroute',
    'Party',
    'unlimited',
    'The lebanese version of cards against humanity: Hilarious, irreverent party game where players match cards to create outrageous and politically incorrect phrases. ',
  ],
  Chess: [
    'Chess',
    'Classic',
    '20-30mins',
    "Chess: The classic strategy board game where players strategically maneuver their pieces to outwit and checkmate their opponent's king, testing their tactical skills and foresight in a battle of wits and strategy.",
  ],

  Tawlit_Zaher: [
    'Tawlit Zaher',
    'Classic',
    '10-15mins',
    'Classic lebanese game no introduction needed',
  ],

  Avalon: [
    'Avalon',
    'Social',
    '20-30 mins',
    "A social deduction game where players embark on quests as knights of King Arthur's court or infiltrators, working to uncover allies and foes through deduction, deception, and strategic voting, in a battle for the fate of Camelot.",
  ],
  Mastermind: [
    'Mastermind',
    'Codebreaking',
    '10-15 mins',
    'A code-breaking board game where one player creates a secret code and the other player tries to guess it using deduction and logic, with limited clues provided after each guess, testing mental acuity and strategic thinking.',
  ],
  Sudoku: [
    'Sudoku',
    'Classic',
    'unlimited',
    'A numbers puzzle game where players fill a 9x9 grid with numbers so that each row, column, and 3x3 subgrid contains all the digits from 1 to 9, challenging logic and problem-solving skills with increasingly difficult puzzles.',
  ],
  Mot_Meles: [
    'Mots Meles',
    'Word puzzle',
    '20-30mins',
    'A word search puzzle game where players find hidden words within a grid of letters, testing vocabulary, pattern recognition, and concentration skills while enjoying a relaxing and engaging challenge.',
  ],
  Micado: [
    'Micado',
    'Classic',
    '10-15 mins',
    'A dexterity game where players take turns picking up sticks from a pile without disturbing the others, testing precision, patience, and hand-eye coordination in a fun and challenging balancing act.',
  ],
  Battleship: [
    'Battleship',
    'Classic',
    '15-20 mins',
    "Battleship: A strategic guessing game where players deploy ships on a grid and take turns calling out coordinates to locate and sink their opponent's fleet, requiring deduction, planning, and a bit of luck to emerge victorious in this naval warfare showdown.",
  ],
  Stratego: [
    'Stratego',
    'Strategy',
    '20-30 mins',
    "A classic strategy board game where players command armies and attempt to capture their opponent's flag while defending their own, relying on deception, tactics, and memory to outmaneuver and defeat the enemy forces in a battle of wits.",
  ],
  Monopoly_Ultimate_Banking: [
    'Monopoly Utimate Banking',
    'Classic',
    '30-45 mins',
    'Monopoly is a classic board game where players roll dice, move around the board, and buy, trade, and develop properties to amass wealth. The goal is to bankrupt opponents by charging them rent when they land on owned properties, ultimately becoming the last player with money and assets remaining.',
    '',
    'https://www.youtube.com/watch?v=YUZzF72bQbw',
  ],
  Seven_Wonders_Duel: [
    '7 Wonders Duel',
    'Civilization',
    '30-45 mins',
    'Two-player card game. Build civilizations, construct wonders, and outscore opponent.',
    'https://www.youtube.com/watch?v=SxQkMRUvCJ8',
    'https://www.youtube.com/watch?v=SNzJklxFQQ0',
  ],
  Machrou3_Ra2is: ['Machrou3 Ra2is', '', '80 mins', ''],
  Codenames_Pictures: [
    'Codenames Pictures',
    'Party',
    '15-20 mins',
    'A word association game where players give one-word clues to help their teammates identify secret agents hidden among a grid of pictures, while avoiding clues that might lead them to innocent bystanders or enemy agents, requiring teamwork, creativity, and deductive reasoning to win.',
  ],
  Dixit: [
    'Dixit',
    'Party',
    '30 mins',
    'A creative and imaginative party game where players use beautifully illustrated cards to tell stories and make associations, scoring points by guessing which card matches a given clue, while avoiding being too obvious or too obscure.',
  ],
  Carcassone: [
    'Carcassone',
    'Tile-Laying',
    '35 mins',
    "Carcassonne: A tile-laying board game where players strategically place tiles to build cities, roads, and fields, aiming to claim territory and earn points. With each tile placement, players can choose to complete features, expand their influence, or disrupt opponents' plans in this engaging game of medieval city-building and strategy.",
  ],
  Rummikub: [
    'Rummikub',
    'Title-Laying',
    '20mins',
    'A classic tile-based game where players strategically manipulate numbered tiles to create runs and sets, aiming to be the first to empty their rack. With elements of rummy and mahjong, Rummikub offers a blend of strategy, luck, and skill in a fast-paced and engaging gameplay experience.',
  ],
  Falling_Monkeys: [
    'Falling Monkeys',
    'Party',
    '5-10mins',
    "A dexterity game where players take turns dropping monkeys into a tree structure, trying to land them on specific branches without causing them to fall. It's a fun and challenging game that tests players' hand-eye coordination and aiming skills as they compete to strategically place their monkeys while sabotaging their opponents.",
  ],
  Risk_Games_of_Thrones: [
    'Risk Games of Thrones',
    'Classic',
    '60-90 mins',
    "A strategic board game combining the classic gameplay of Risk with the rich world of George R.R. Martin's A Song of Ice and Fire series. Players vie for control of the Seven Kingdoms of Westeros, commanding armies, forging alliances, and conquering territories in their quest for ultimate power. With familiar elements from the beloved series, including iconic locations and characters, this game offers a thrilling blend of diplomacy, warfare, and political intrigue.",
  ],
  Quatro: [
    'Quatro',
    'Strategy',
    '10 mins',
    "An abstract strategy game where players take turns choosing a piece for their opponent to place on the board, aiming to create a line of four pieces that share a common characteristic (such as color, shape, size, or hollowness). With each move, players must carefully consider both offensive and defensive strategies to outmaneuver their opponent and prevent them from achieving Quarto. It's a game of spatial reasoning, pattern recognition, and tactical planning.",
    '',
    'fxM22VPqgQ4',
  ],
  Quoridor: [
    'Quoridor',
    'Strategy',
    '10 mins',
    "A strategic board game where players navigate their pawn through a maze-like grid while simultaneously placing walls to impede their opponent's progress. The goal is to reach the opposite side of the board before your opponent does. With each move, players must balance offense and defense, seeking the optimal path while thwarting their opponent's advancement. Quoridor is a game of spatial reasoning, foresight, and tactical maneuvering.",
    '',
    '1dMWQ5N2DLg',
  ],
  Squadro: [
    'Squadro',
    'Strategy',
    '10 mins',
    "A two-player abstract strategy game where players compete to move their pieces across the board to reach their opponent's home row. Players can also rotate the board to create new paths and block their opponent's movements. With simple rules but deep strategic possibilities, Squadro offers a unique and engaging gameplay experience that requires careful planning and adaptability.",
  ],
  Codenames_Duet: [
    'Codenames Duet',
    'Deduction',
    '15 mins',
    'A cooperative word association game where two players work together to uncover secret agents hidden among a grid of words. Players must give one-word clues to help their partner identify the correct words while avoiding clues that could lead to bystanders or assassins. With limited guesses and a race against the clock, Codenames Duet offers a challenging and thrilling gameplay experience that tests communication skills and deductive reasoning.',
  ],
  The_voting_game: [
    'The Voting Game',
    'Party',
    'Unlimited',
    'A party game where players take turns asking questions and voting anonymously on which player best fits the description. With questions ranging from humorous to revealing, The Voting Game encourages lively discussions and reveals surprising insights about friends and family, making it a hilarious and entertaining social experience.',
  ],
  Taco_vs_Burrito: [
    'Taco vs Burrito',
    'Card',
    '15-20 mins',
    "A card game where players create delicious dishes by combining various ingredients like meat, toppings, and sauces. Players strategically play cards to build their meals while also playing action cards to sabotage their opponents' dishes. With colorful illustrations and humorous combinations, Taco vs Burrito offers a fun and competitive experience for food lovers of all ages.",
  ],
  El_mamnou3_marghoub: ['El Mamnou3 Marghoub', 'Party', 'Unlimited', ''],
  Connect_four: [
    'Connect four',
    'Classic',
    '5-10 mins',
    'A classic two-player game where players take turns dropping colored discs into a vertically suspended grid. The objective is to be the first to form a line of four discs of your color horizontally, vertically, or diagonally. Connect Four is a simple yet engaging game that requires strategic thinking and anticipation to outmaneuver your opponent and achieve victory.',
  ],
  Hedbanz: [
    'Hedbenz',
    'Party',
    '15-20 mins',
    'A party game where players wear headbands with cards attached to them, each card displaying a different object, animal, or person. Players take turns asking yes or no questions to figure out what card is on their headband. The goal is to guess the card before time runs out, relying on deduction, reasoning, and hints from other players. Hedbanz is a fast-paced and hilarious game that encourages creativity and communication.',
  ],
  Box_against_office: [
    'Box against office',
    'Party',
    'Unlimited',
    'Hilarious, irreverent party game where players match cards to create outrageous and politically incorrect phrases.',
  ],
  Mini_Plakks: [
    'Mini Plakks',
    'Party',
    '5-10 mins',
    'Playing football with you finger, block your enemy and remove all of their defenders to be the unlitimate winner',
  ],
  Cards_Against_Star_Wars: [
    'Cards Against Star Wars',
    'Party',
    'Unlimited',
    'Hilarious, irreverent party game where players match cards to create outrageous and politically incorrect phrases.',
  ],
  Tossit: [
    'Tossit',
    'Party',
    'Unlimited',
    "Combination of dart and petanque where instead of throwing a big heavy ball you're throwing a rubber flat dart",
    '',
    'CqbfIX3lFq8',
  ],
  Yellowstone: [
    'Yellowstone',
    'Social',
    'Unlimited',
    "John Doe and his ranch are in a crisis, it is up to the players to suggest solutions, however some player won't know what the crisis is and are working against John. Who are the imposters and who are the saviors ",
    '',
    'S0sm9-8wdIg',
  ],
  Tag_someone_who: [
    'Tag someone who',
    'Party',
    'Unlimited',
    "each players is assigned a color, and you'll be able to tag the player that you think would suit the action or description that is written on the card",
    '',
    'gg2kiAOy1IM',
  ],
  Murder_we_wrote: [
    'Murder we wrote',
    'Party',
    'Unlimited',
    'Each player create the weridest and funniest murder scene using the cards in their hand and the victim that will be placed in the middle',
    '',
    'qKlnNZ9qWZ0',
  ],
  Priorities: [
    'Priorities',
    'Party',
    'Unlimited',
    'How much does your friends know you! Play against the game and spell out Priorities',
    '',
    'wqSwbC_JxME',
  ],
};
